### _main.R: REPLICATION OF FIGURES AND TABLES FROM ``The Effects of Prohibiting Marriage Bars: The Case of U.S. Teachers'' 
### UPDATED: DECEMBER 2025
### AUTHORS: AMY KIM (kimamy@princeton.edu) AND CAROLYN TSAO (carolyntsao@microsoft.com)

############################################################
# USER CONFIGURATION
# Set all paths and options here before running.
############################################################

# --- Replication folder ---
# TODO: Set root to the path of this folder on your machine
root = "<YOUR PATH>/jeh_replication"
# TEMP
root = "~/Princeton Dropbox/Amy Kim/marriagebar/jeh_replication_new"
setwd(root)

data = paste0(root, "/data")

# --- Raw data paths ---
# Only needed if link1-3 individual-level files are missing (see README.md).
# rawdata: folder containing IPUMS extract file(s)
#   ipums_format == "multi":  expects census_1910.csv ... census_1950.csv
#   ipums_format == "single": expects ipums_all.csv
rawdata          <- paste0(data, "/raw")
censustreepath   <- "<YOUR PATH>/censustree"      # folder with 1910_1920.csv, 1920_1930.csv, 1930_1940.csv
# TEMP
censustreepath <- "~/Princeton Dropbox/Amy Kim/marriagebar/ipums_raw"
retailsales_file <- paste0(data, "/retailsales/retailsales_data.xls")

# --- IPUMS extract format ---
# "multi"  : separate per-year CSV files (census_1910.csv ... census_1950.csv) in rawdata/
# "single" : one combined CSV file (ipums_all.csv) containing all census years in rawdata/
#            The single extract must contain a YEAR column identifying the census year.
ipums_format <- "single"

# --- Optional: regenerate county-level summary files from scratch ---
# The countysumm*.csv files are provided directly and do not need to be regenerated.
# Set to TRUE only if you want to verify them from raw IPUMS data.
run_county_section <- TRUE

# load packages and functions ----
require(glue)
require(tidyverse)
require(sandwich)
require(fixest)
require(MatchIt)
require(stargazer)
library(DBI)
library(duckdb)
library(readxl)

# toggles ----
verbose = TRUE # toggle true to see figures and tables outputted as code runs
save = TRUE # toggle true to save figures and tables to output folders

# set colors ----
mw_col  = "#8751A4"
sw_col  = "#2D1B37"
men_col = "#C8ADD7"

control_col = "#46b97a"
treat_col   = "#B94685"

# RUNNING HELPER FILE ----
source("code/helper.R")

# importing data ----
# Check whether all 6 data files exist; if any are missing, run clean_data.R first.
# Note: countysumm*.csv files are provided in the package. The link1-3 files must be
# generated from raw IPUMS data — see README.md and code/clean_data.R for instructions.
data_files <- c(
  glue("{data}/countysumm.csv"),
  glue("{data}/countysumm_blk.csv"),
  glue("{data}/countysumm_wht.csv"),
  glue("{data}/link1_swt_indiv.csv"),
  glue("{data}/link2_mwnilf_indiv.csv"),
  glue("{data}/link3_swnilf_indiv.csv")
)
missing_files <- data_files[!file.exists(data_files)]
if (length(missing_files) > 0) {
  message("The following data files are missing and will be generated by clean_data.R:")
  message(paste(" -", missing_files, collapse = "\n"))
  message("Running code/clean_data.R ... (this may take a while)")
  source("code/clean_data.R")
}

## Cross-Sectional County x Year-level Data (used for Tables 1, 2, 4 and Figures 1, 2, 3)
countysumm      <- read_csv(glue("{data}/countysumm.csv"))
countysumm_blk  <- read_csv(glue("{data}/countysumm_blk.csv"))
countysumm_wht  <- read_csv(glue("{data}/countysumm_wht.csv"))

# filtering to preferred sample of balanced panel of treatment and control counties
neighbor       <- countysumm     %>% filter(neighbor_samp == 1 & mainsampall == 1)
neighbor_blk   <- countysumm_blk %>% filter(neighbor_samp == 1 & mainsampblk == 1)
neighbor_wht   <- countysumm_wht %>% filter(neighbor_samp == 1 & mainsampwht == 1)

## Linked Individual-level Data (used for Tables 3 and 5)
link1_swt          <- read_csv(glue("{data}/link1_swt_indiv.csv"))
link2_mwnilf       <- read_csv(glue("{data}/link2_mwnilf_indiv.csv"))
link3_swnilf       <- read_csv(glue("{data}/link3_swnilf_indiv.csv"))

# RUNNING TABLES FILE ----
source("code/tables.R")

# RUNNING FIGURES FILE ----
source("code/figures.R")
